#!/usr/bin/env bash
#
# Copyright 2019 Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "$SOWLIB/pluginutils"

set -eo pipefail

getRequiredValue path "path" PLUGINCONFIGJSON # path to root directory of kustomize repo
getRequiredValue kustomization "kustomization" PLUGINCONFIGJSON # path to directory containing kustomization.yaml file, relative to $path
getValueList kustomize_flags_deploy "flags.deploy" PLUGINCONFIGJSON
getValueList kustomize_flags_delete "flags.delete" PLUGINCONFIGJSON

fullpath="$path/$kustomization"
if [[ ! -f "$fullpath/kustomization.yaml" ]]; then
    fail "kustomization.yaml not found in directory '$fullpath'"
fi

deploy() {
    info "Running kustomize build $fullpath ..."
    exec_cmd_override "kustomize build \"$fullpath\" $(echo "${kustomize_flags_deploy[@]}")"
}

delete() {
    info "Running kustomize build $fullpath ..."
    exec_cmd_override "kustomize build \"$fullpath\" $(echo "${kustomize_flags_delete[@]}")"
}

# workaround - exec_cmd can't be used since it uses 'echo' (in verbose mode), which interferes with the pipe.
exec_cmd_override() {
    local cmd="$1"
    if [ -n "$VERBOSE" ]; then
        echo "$cmd"
    fi
    eval $(echo "$cmd") > "$dir/manifest.yaml"
}

case "$1" in
    deploy) deploy "$@";;
    delete) delete "$@";;
    *) fail "unsupported action $1"
esac
