#!/bin/bash

source "$SOWLIB/pluginutils"

getRequiredValue repo "repo" PLUGINCONFIGJSON
getValue tag "tag" PLUGINCONFIGJSON
getValue branch "branch" PLUGINCONFIGJSON
getValueList files "files" PLUGINCONFIGJSON

if [ -z "$tag$branch" ]; then
    fail "either 'tag' or 'branch' attribute is required"
fi
if [ -n "$tag" ]; then
    if [ -n "$branch" ]; then
        fail "only 'tag' or 'branch' attribute should be given"
    fi
    # tag is given
    prefix="refs/tags/"
    ref="$tag"
else
    # branch is given
    prefix=
    ref="$branch"
fi

repo_path="$dir/repo"

deploy() {
    info "Cloning repo $repo ..."

    if [ ! -d "$repo_path" ]; then
        git clone --depth 1 --no-checkout --branch $ref "$repo" "$repo_path"
    fi
    (
        cd "$repo_path"
        git fetch --depth 1 -f origin $prefix$ref
        git reset $ref 1> /dev/null
        git checkout $ref "${files[@]}"
    )
}

delete() {
    true
}

case "$1" in
    deploy|prepare) deploy "$@";;
    delete|cleanup) delete "$@";;
    *) fail "unsupported action $1"
esac
