#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0


source "$SOWLIB/pluginutils"

set -eo pipefail

getRequiredValue path "path" PLUGINCONFIGJSON # path to root directory of kustomize repo
getRequiredValue kustomization "kustomization" PLUGINCONFIGJSON # path to directory containing kustomization.yaml file, relative to $path
getValueList editArgs "args" PLUGINCONFIGJSON # arguments for 'kustomize edit' command

fullpath="$path/$kustomization"
if [[ ! -f "$fullpath/kustomization.yaml" ]]; then
    fail "kustomization.yaml not found in directory '$fullpath'"
fi
cpdir="$dir/edit"

deploy() {
    rm -rf "$cpdir"
    mkdir -p "$cpdir"
    cp -R "$path/." "$cpdir/"
    (
        cd "$cpdir/$kustomization"
        exec_cmd kustomize edit $(echo "${editArgs[@]}") 
    )
}

delete() {
    verbose "nothing to do on delete"
}

case "$1" in
    deploy) deploy "$@";;
    delete) delete "$@";;
    *) fail "unsupported action $1"
esac
