#!/usr/bin/env bash
#
# Copyright 2019 Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "$SOWLIB/pluginutils"
source "$SOWLIB/k8s"

if [ -d "$GEN" ]; then
  export HELM_HOME="$GEN/.helm"
fi

helminit() {
    helm init --service-account=tiller
}

PLUGIN_setup "$2"

K8S_setKubeConfig "$PLUGININSTANCE" "$dir/kubeconfig"

case $1 in
  deploy) K8S_assurepods "K8S_checkpod -d kube-system tiller-deploy" "helminit";;
  delete) kubectl -n kube-system delete deployment tiller-deploy || true;;
  *) fail "unsupported command $1";;
esac

