#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0


source "$SOWLIB/pluginutils"
source "$PLUGIN/lib/k8s"

manifestdir="$dir/manifests"
mkdir -p "$manifestdir"

equivalences=( )

loadHandlers()
{
  local d
  local h
  local e
  local equis=( )

  for d in "$@"; do
    if [ -n "$d" ]; then
      if [ -d "$d/handlers" ]; then
        for h in "$d/handlers"/*; do
          if [ -f "$h" ]; then
            source "$h"
          fi
        done
      fi
      for e in "$d"/*.equiv; do
        if [ -f "$e" ]; then
          e="$(spiff merge --json "$e")"
          getJSONList equis equivalences e
          equivalences=( "${equivalences[@]}" "${equis[@]}" )
        fi
      done
    fi
  done
}

loadHandlers "$PLUGIN" "$CURRENT/lib/kubectl" "$PRODUCTDIR/lib/kubectl" "$SOW_HOME"

for h in "${@:3}"; do
  verbose "loading handler $h"
  f="$(lookupFile "$h")"
  if [ -n "$f" ]; then
    source "$f"
  else
    fail "handler plugin '$j' not found"
  fi
done

DEFKUBE=( )
getJSONList MANIFESTS "" PLUGINCONFIGJSON

LEN="${#MANIFESTS[@]}"

if [ $LEN -eq 0 ]; then
  info no manifests found
fi

cmd_echo()
{
  if [ "$2" = "deploy" ]; then
    if [ "$1" != "deploy" ]; then
      return
    fi
    shift
  fi
  echo "${@:2}"
}

cmd_forget()
{
  if [ ${#kube[@]} -eq 0 -o -z "${kube[1]}" ]; then
    fail no or empty kubeconfig configured
  fi
  if [ $# -ne 5 ]; then
    fail "forget:  <name> <namespace> <kind> <apiVersion>"
  fi
  setKubeConfig "${kube[@]}" "$TMP_KUBECONFIG"
  api="$(getAPIServerFromKubeconfig "$TMP_KUBECONFIG")"

  local key
  getObjectKey key "$2" "$3" "$4" "$5"
  local def
  getJSON def 'clusters["'$api'"].manifests["'$key'"]' deployed
  if [ -n "$def" ]; then
    found "forget $2/$3/$4/$5 for $api ($key)"
    deljsonkey deployed 'clusters["'$api'"].manifests["'$key'"]'
  fi
}

setKubeConfig()
{
  if [ $1 = value ]; then
    local kubeconfig
    if [[ "$2" != /* ]]; then
      kubeconfig="$ROOT/$2"
    else
      kubeconfig="$2"
    fi
    cp "$kubeconfig" "$3"
    verbose "    using $kubeconfig"
  else
    echo "$2" > "$3"
    verbose "    using inline kubeconfig"
  fi
}

# $1: action
# $2: kubeconfig file
# $3: manifest file
# $4: retry attempts (defaults to 1)
# $5: retry waiting time in seconds (defaults to 10)
exec_action()
{
  local name
  local namespace
  local kind
  local apiversion
  local objectkey
  local objectentry
  local res

  getManifestInfo "$(spiff merge --json "$3")"

  local group="${apiversion%/*}"
  local suf
  local ns
  if [ "$group" = "$apiversion" ]; then
    suf=.
    group=core
  else
    suf=".$group"
  fi
  if [ -n "$namespace" ]; then
    ns="-n $namespace"
  else
    ns=
  fi
  if [ "$1" = "delete" ]; then
    res="$(kubectl --kubeconfig "$2" $ns get "$kind$suf" --field-selector "metadata.name=$name" -o jsonpath={.items})"
    if [ "$res" = '[]' ]; then
      info "$kind $1 ($2) already deleted"
      return
    fi
  fi
  local f="action_${1}_${kind}_${group//\./_}"
  if _is_function "$f"; then
    verbose "    using handler $f"
    $f "$name" "$namespace" "$2" "$3"
  else
    local attempts=${4:-""}
    local backoff=${5:-""}
    if [ -z "$attempts" ]; then
      attempts=5
    fi
    if [ -z "$backoff" ]; then
      backoff=15
    fi
    case "$1" in
      deploy)
        while true; do
          if exec_cmd kubectl --kubeconfig "$2" apply -f "$3" ; then
            break
          else
            attempts=$(( attempts - 1 ))
            if [[ $attempts -gt 0 ]]; then
              info "command failed, waiting for $backoff seconds and trying again ($attempts times)"
              sleep $backoff
            else
              fail "kubectl command failed and retry limit reached"
            fi
          fi
        done
        ;;
      delete)
        while true; do
          if exec_cmd kubectl --kubeconfig "$2" delete -f "$3" ; then
            break
          else
            attempts=$(( attempts - 1 ))
            if [[ $attempts -gt 0 ]]; then
              info "command failed, waiting for $backoff seconds and trying again ($attempts times)"
              sleep $backoff
            else
              fail "kubectl command failed and retry limit reached"
            fi
          fi
        done
        ;;
    esac
  fi
}

exec_manifest()
{
  local cmd="$1"
  local type="$2"
  local kube="$3"
  local index="$4"
  local manifest="$5"
  local retry_attempts="$6"
  local retry_wait="$7"

  local kubeconfig="$TMP_KUBECONFIG"
  setKubeConfig "$type" "$kube" "$kubeconfig"
  api="$(getAPIServerFromKubeconfig "$kubeconfig")"
  ord="${#executed["$api"]}"

  getManifestInfo "$manifest" "entry $index" "$ord"

  local base
  if [ -n "$namespace" ]; then
    found "manifest for $kind($apiversion): $namespace/$name"
    base="$manifestdir/$index-$kind.$namespace.$name"
  else
    found "manifest for $kind($apiversion): $name"
    base="$manifestdir/$index-$kind.$name"
  fi

  local file="$base.yaml"

  if [ "$cmd" == deploy ]; then
    echo "$manifest" | spiff merge - >"$file"
    exec_action "$cmd" "$kubeconfig" "$file" "$retry_attempts" "$retry_wait"
    setjsonvalue deployed 'clusters["'$api'"].kubeconfig' "$(cat "$kubeconfig")"
    setjsonjson deployed 'clusters["'$api'"].manifests["'$objectkey'"]' "$objectentry"
    executed["$api"]="${executed["$api"]} $objectkey"
  else
    if [ -f "$file" ]; then
      exec_action "$cmd" "$kubeconfig" "$file" "$retry_attempts" "$retry_wait"
      deljsonkey deployed 'clusters["'$api'"].manifests["'$objectkey'"]'
    fi
  fi
}

TMP_KUBECONFIG="$dir/kubeconfig.tmp"
TMP_MANIFEST="$dir/manifest.tmp"

cleanup_deployments()
{
  local apis
  local val
  getJSON val "clusters" deployed
  if [ -z "$val" ]; then
    return
  fi
  getKeys apis "clusters" deployed
  for api in "${apis[@]}"; do
    local keys
    getKeys keys 'clusters["'"$api"'"].manifests' deployed
    local kubeconfig
    local cur=( ${executed[$api]} )
    getValue kubeconfig 'clusters["'"$api"'"].kubeconfig' deployed
    echo "$kubeconfig" >"$TMP_KUBECONFIG"
    info "cluster $api"
    found "  found deployed objects: ${#keys[@]}"
    found "  found currect objects: ${#cur[@]}"
    declare -A obsolete ords names
    local ordered=( )

    for key in "${keys[@]}"; do
      if ! contains "$key" "${cur[@]}"; then
        local objectentry
        local name
        local namespace
        local kind
        local apiversion
        local apigroup

        getJSON objectentry 'clusters["'"$api"'"].manifests["'"$key"'"]' deployed
        getManifestInfoFromEntry
        getAPIGroupFromVersion apigroup "$apiversion"

        # compatibility handling: migrate to new key structure
        local new
        getObjectKey new "$name" "$namespace" "$kind" "$apiversion"
        if contains "$new" "${cur[@]}"; then
            found "  migrating deployed object $name/$namespace/$kind/$apigroup to new key structure"
            deljsonkey deployed 'clusters["'"$api"'"].manifests["'"$key"'"]'
            continue 2
        fi

        local alt=( )
        getEquivalences alt "$apiversion" "$kind"

        for a in "${alt[@]}"; do
          local altkey
          local altkind
          local altgroup
          getAPIGroupFromManifest altgroup a
          getValue altkind kind a
          getObjectKeyByGroup altkey "$name" "$namespace" "$altkind" "$altgroup"
          if contains "$altkey" "${cur[@]}"; then 
            found "  migrating deployed object $name/$namespace from $kind/$apigroup to $altkind/$altgroup"
            deljsonkey deployed 'clusters["'"$api"'"].manifests["'"$key"'"]'
            continue 2
          fi
        done

        if [ -n "$namespace" ]; then
          names[$key]="$kind($apiversion): $namespace/$name"
        else
          names[$key]="$kind($apiversion): $name"
        fi

        if [ -z "$ord" ]; then
          ord=0
        fi
        obsolete[$key]="$manifest"
        ords[$key]="$ord"
        local new=( )
        local found=
        for k in "${ordered[@]}"; do
          if [ -z "$found" -a ${ords[$k]} -lt $ord ]; then
            new=( "${new[@]}" "$key" )
            found=X
          fi
          new=( "${new[@]}" "$k" )
        done
        if [ -z "$found" ]; then
          ordered=( "${new[@]}" "$key" )
        else
          ordered=( "${new[@]}" )
        fi
      fi
    done

    if [ ${#ordered[@]} -gt 0 ]; then
      info "  found deployed obsolete objects: ${#ordered[@]}"
      for key in "${ordered[@]}"; do
        echo "${obsolete[$key]}" > "$TMP_MANIFEST"
        found "    ${names[$key]}"
        exec_action delete  "$TMP_KUBECONFIG" "$TMP_MANIFEST"
        deljsonkey deployed 'clusters["'"$api"'"].manifests["'"$key"'"]'
      done
    fi
    getKeys keys 'clusters["'"$api"'"].manifests' deployed
    if [ ${#keys[@]} -eq 0 ]; then
      deljsonkey deployed 'clusters["'"$api"'"]'
    fi
  done
}

save()
{
  x=$?
  if [ $x -ne 0 ]; then
    handle_error $x
  fi
  if [ -n "$deployed" ]; then
    if [ -z "$DRYRUN" ]; then
      if [ -f "$state/deployed.json" ]; then
        mv "$state/deployed.json" "$state/deployed.json.bak"
      fi
      echo "$deployed" > "$state/deployed.json"
      deployed=""
    fi
  fi
  if [ -z "$KEEP_TEMPFILES" ]; then
    rm -f "$TMP_KUBECONFIG" "$TMP_MANIFEST"
  fi
}

showEquivalences()
{
  if [ -n "$VERBOSE" ]; then
    local e
    local e
    if [ ${#equis[@]} -gt 0 ]; then
      found "using equivalences:"
      for l in "${equis[@]}"; do
        local prefix="* -"
        local list=( )
        getJSONList list "" l
        for e in "${list[@]}"; do
          echo "$prefix $e"
          prefix="  -"
        done
      done
    fi
  fi
}

getEquivalences()
{
  eval $1='( )'
  local curgrp
  getAPIGroupFromVersion curgrp "$2"
  for l in "${equis[@]}"; do
    local list=( )
    getJSONList list "" l
    local cnt=0
    for e in "${list[@]}"; do
      local apigroup
      local kind
      getAPIGroupFromManifest apigroup e
      getValue kind kind e
      if [ "$curgrp" == "$apigroup" -a "$3" == "$kind" ]; then
        eval $1='( ${list[@]:0:$cnt} ${list[@]:$((cnt + 1))} )'
        return
      fi
      cnt=$((cnt + 1))
    done
  done
}

execute_manifest()
{
  exec_manifest $1 "${kube[@]}" "$i-$2" "$3" "$4" "$5"
}

execute_file()
{
  local j="$2"
  local f="$3"
  local file

  file="$(lookupFile "$f")"
  if [ -z "$file" ]; then
    fail "entry $i:$j: $f not found"
  fi
  while IFS= read -r line; do
    exec_manifest $1 "${kube[@]}" "$i-$j" "$line" "$4" "$5"
  done < <(spiff merge --json "$file" | $order)
}

execute_entry()
{
  local i=$2
  local entry="$3"
  local nested

  getValueOrJSON kube kubeconfig entry
  if [ ${#kube[@]} -eq 0 ]; then
    kube=( "${DEFKUBE[@]}" )
  else
    nested=X
  fi

  local retry_attempts
  local retry_wait
  local files=( )
  local args=( )
  local lequis=( )
  local manifests=( )

  getValue retry_attempts "retry.attempts" entry
  getValue retry_wait "retry.wait" entry
  getJSONList manifests manifests entry
  getJSONList lequis equivalences entry
  equis=( "${equis[@]}" "${lequis[@]}" )

  if [ ${#manifests[@]} -ne 0 ]; then
    if [ ${#kube[@]} -eq 0 -o -z "${kube[1]}" ]; then
      fail no or empty kubeconfig configured
    fi
    executionLoop "$1" manifests execute_manifest "$retry_attempts" "$retry_wait"
  else
    getValueList files files entry
    getValueList args command entry
    if [ ${#files[@]} -ne 0 ]; then
      if [ ${#args[@]} -ne 0 ]; then
        fail "entry $i: only files or command possible"
      fi
      if [ ${#kube[@]} -eq 0 -o -z "${kube[1]}" ]; then
        fail no or empty kubeconfig configured
      fi
      executionLoop "$1" files execute_file "$retry_attempts" "$retry_wait"
    elif [ ${#args[@]} -ne 0 ]; then
      found "command: ${#args[@]}: ${args[@]}"
      if _is_function "cmd_${args[0]}"; then
         "cmd_${args[0]}" "$1" "${args[@]:1}"
      else
        fail "entry $i: command ${args[0]} not supported by kubectl plugin"
      fi
    elif [ -z "$nested" ]; then
        exec_manifest $1 "${kube[@]}" "$i" "$entry"
    else
      getJSON tmpf files entry
      getJSON tmpc command entry
      if [ -z "$tmpf$tmpc" ]; then
        fail "entry $i: kubeconfig option must be combined with manifests or command option"
      fi
    fi
  fi
}

execute()
{
  trap save EXIT ERR 2
  declare -A executed
  local deployed="{}"
  local equis=( "${equivalences[@]}" )

  if [ -f "$state/deployed.json" ]; then
    deployed="$(cat "$state/deployed.json")"
  fi
  executionLoop "$1" MANIFESTS execute_entry a
  showEquivalences
  cleanup_deployments
  save
}

deploy() {
  execute deploy "$@"
}

delete() {
  execute delete "$@"
}

case "$1" in
    deploy) deploy "${@:1}";;
    delete) delete "${@:1}";;
    *) fail "unsupported action $1"
esac
