#!/bin/bash -e

source "$SOWLIB/utils"

field_path="${2:-terraform}"
dir="$GENDIR/$field_path"
state="$STATEDIR/$field_path"
mkdir -p "$dir" "$state"

jq ."$field_path".values <<< "$DEPLOYMENTJSON" > "$dir/terraform.tfvars"

source="$(jq -r ".$field_path.source"  <<< "$DEPLOYMENTJSON")"

if [ "$source" == null ]; then
    fail "source attribute required for field $1"
fi

deploy() {
    (
        cd "$dir"
        exec_cmd terraform init "$source"
        exec_cmd terraform apply -auto-approve -var-file="$dir/terraform.tfvars" -state="$state/terraform.tfstate" "$source"
    )
}

delete() {
    if [ -f "$state/terraform.tfstate" ]; then
        (
            cd "$dir"
            exec_cmd terraform destroy -force -var-file="$dir/terraform.tfvars" -state="$state/terraform.tfstate" "$source"
        )
    fi
}

case "$1" in
    deploy) deploy "$@";;
    delete) delete "$@";;
    *) fail "unsupported action $1"
esac
