#!/bin/bash -e

source "$SOWLIB/pluginutils"

jq .values <<< "$PLUGINCONFIGJSON" > "$dir/terraform.tfvars"

getValue source soure PLUGINCONFIGJSON

if [ -z "$source" ]; then
    fail "source attribute required"
fi

deploy() {
    (
        cd "$dir"
        exec_cmd terraform init "$source"
        exec_cmd terraform apply -auto-approve -var-file="$dir/terraform.tfvars" -state="$state/terraform.tfstate" "$source"
    )
}

delete() {
    if [ -f "$state/terraform.tfstate" ]; then
        (
            cd "$dir"
            exec_cmd terraform destroy -force -var-file="$dir/terraform.tfvars" -state="$state/terraform.tfstate" "$source"
        )
    fi
}

case "$1" in
    deploy) deploy "$@";;
    delete) delete "$@";;
    *) fail "unsupported action $1"
esac
